import type { JourneyStage } from "./site";

export const journeyStages: JourneyStage[] = [
  {
    id: "problem",
    label: "PROBLEM",
    statement: "I see problems everywhere.",
    example: "Creators need bulk download + clip pipelines without per-minute cloud tax.",
    productSlug: "downitx",
    accent: "#3d8bff",
  },
  {
    id: "observation",
    label: "OBSERVATION",
    statement: "I watch how people actually work.",
    example: "Bloggers still bounce between Canva, ChatGPT, and a scheduler for every pin.",
    productSlug: "pinquill",
    accent: "#e11d48",
  },
  {
    id: "idea",
    label: "IDEA",
    statement: "Then I shape a product bet.",
    example: "WhatsApp help should draft locally — humans approve before anything sends.",
    productSlug: "wasup",
    accent: "#25d366",
  },
  {
    id: "experiment",
    label: "EXPERIMENT",
    statement: "I test the workflow before I scale it.",
    example: "Authority content for a niche market — expert review before publish.",
    productSlug: "pickleball-deutsch",
    accent: "#ffb020",
  },
  {
    id: "product",
    label: "PRODUCT",
    statement: "I ship something people can use.",
    example: "DownitX, PinQuill, Wasup, and Pickleball Deutsch are live multilingual products.",
    productSlug: "downitx",
    accent: "#3d8bff",
  },
  {
    id: "users",
    label: "USERS",
    statement: "I observe behavior and tighten the loop.",
    example: "Desktop installers, BYOK trials, and local queues reveal what creators actually finish.",
    productSlug: "pinquill",
    accent: "#e11d48",
  },
  {
    id: "growth",
    label: "GROWTH",
    statement: "I improve the system that acquires and converts.",
    example: "SEO hubs, multilingual routes, and clear pricing pages compound what shipped.",
    productSlug: "pickleball-deutsch",
    accent: "#ffb020",
  },
];
