export type CourtSurface = "indoor" | "outdoor" | "both";

export type PickleballCourt = {
  id: string;
  city: string;
  state: string;
  name: string;
  surface: CourtSurface;
  notes: string;
  guideUrl: string;
};

/** Curated seed from Pickleball Deutsch city-guide coverage — expandable. */
export const pickleballCourts: PickleballCourt[] = [
  {
    id: "berlin-1",
    city: "Berlin",
    state: "Berlin",
    name: "Berlin pickleball spots",
    surface: "both",
    notes: "Growing metro scene — indoor clubs + outdoor public courts.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "hamburg-1",
    city: "Hamburg",
    state: "Hamburg",
    name: "Hamburg courts",
    surface: "both",
    notes: "Northern hub with club and open-play options.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "munich-1",
    city: "Munich",
    state: "Bavaria",
    name: "München courts",
    surface: "both",
    notes: "Strong Bavarian scene; check club schedules for open play.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "cologne-1",
    city: "Cologne",
    state: "North Rhine-Westphalia",
    name: "Köln courts",
    surface: "indoor",
    notes: "NRW cluster — indoor-friendly year-round options.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "frankfurt-1",
    city: "Frankfurt",
    state: "Hesse",
    name: "Frankfurt courts",
    surface: "both",
    notes: "Rhine-Main area; mix of clubs and shared sports halls.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "stuttgart-1",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    name: "Stuttgart courts",
    surface: "both",
    notes: "Southwest Germany coverage via city guides.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "duesseldorf-1",
    city: "Düsseldorf",
    state: "North Rhine-Westphalia",
    name: "Düsseldorf courts",
    surface: "indoor",
    notes: "NRW metro — verify hall bookings for peak hours.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "leipzig-1",
    city: "Leipzig",
    state: "Saxony",
    name: "Leipzig courts",
    surface: "both",
    notes: "Eastern Germany growth market.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "dresden-1",
    city: "Dresden",
    state: "Saxony",
    name: "Dresden courts",
    surface: "outdoor",
    notes: "Seasonal outdoor play more common — confirm winter options.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "hannover-1",
    city: "Hannover",
    state: "Lower Saxony",
    name: "Hannover courts",
    surface: "both",
    notes: "Central North coverage.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "nuremberg-1",
    city: "Nuremberg",
    state: "Bavaria",
    name: "Nürnberg courts",
    surface: "both",
    notes: "Franconia / Bavaria secondary hub.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "bremen-1",
    city: "Bremen",
    state: "Bremen",
    name: "Bremen courts",
    surface: "indoor",
    notes: "Compact city scene — check club open play.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "dortmund-1",
    city: "Dortmund",
    state: "North Rhine-Westphalia",
    name: "Dortmund courts",
    surface: "indoor",
    notes: "Ruhr area cluster with nearby cities.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "essen-1",
    city: "Essen",
    state: "North Rhine-Westphalia",
    name: "Essen courts",
    surface: "indoor",
    notes: "Ruhr coverage — pair with Düsseldorf/Cologne guides.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "freiburg-1",
    city: "Freiburg",
    state: "Baden-Württemberg",
    name: "Freiburg courts",
    surface: "outdoor",
    notes: "Southwest outdoor-friendly climate.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "heidelberg-1",
    city: "Heidelberg",
    state: "Baden-Württemberg",
    name: "Heidelberg courts",
    surface: "both",
    notes: "Rhein-Neckar region.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "mannheim-1",
    city: "Mannheim",
    state: "Baden-Württemberg",
    name: "Mannheim courts",
    surface: "both",
    notes: "Near Heidelberg — shared regional scene.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "augsburg-1",
    city: "Augsburg",
    state: "Bavaria",
    name: "Augsburg courts",
    surface: "both",
    notes: "Bavaria secondary market near Munich.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "karlsruhe-1",
    city: "Karlsruhe",
    state: "Baden-Württemberg",
    name: "Karlsruhe courts",
    surface: "both",
    notes: "Southwest corridor coverage.",
    guideUrl: "https://pickleballdeutch.com/",
  },
  {
    id: "bonn-1",
    city: "Bonn",
    state: "North Rhine-Westphalia",
    name: "Bonn courts",
    surface: "indoor",
    notes: "Near Cologne — check joint open-play listings.",
    guideUrl: "https://pickleballdeutch.com/",
  },
];

export const germanStates = [...new Set(pickleballCourts.map((c) => c.state))].sort();
