import type { Project } from "./site";

export const projects: Project[] = [
  {
    slug: "reelerx-saas",
    title: "ReelerX SaaS",
    summary: "AI short-form video product from idea to live users.",
    problem: "Creators need faster reel production without losing quality.",
    role: "Founder / Full-stack / AI pipeline",
    tech: ["Next.js", "Workers", "LLM", "FFmpeg"],
    result: "Live product with automated generation pipeline",
    category: "SAAS",
    status: "LIVE",
    year: 2025,
  },
  {
    slug: "voice-agent-lab",
    title: "Voice Agent Lab",
    summary: "Realtime voice experiments for product guidance.",
    problem: "Support and onboarding are slow in text-only flows.",
    role: "Builder / AI systems",
    tech: ["WebRTC", "STT/TTS", "Tool calling"],
    result: "Experimental agent loops with measurable latency",
    category: "AI",
    status: "EXPERIMENT",
    year: 2026,
  },
  {
    slug: "growth-sites",
    title: "Conversion Websites",
    summary: "High-intent landing systems for digital businesses.",
    problem: "Traffic without conversion architecture wastes spend.",
    role: "Design + development + SEO",
    tech: ["Next.js", "SEO", "Analytics"],
    result: "Faster pages with clearer conversion paths",
    category: "WEB",
    status: "SHIPPED",
    year: 2024,
  },
  {
    slug: "ops-automation",
    title: "Ops Automation Fabric",
    summary: "Webhook-driven workflows replacing manual ops.",
    problem: "Repetitive ops tasks slow product teams.",
    role: "Systems designer",
    tech: ["Workers", "Webhooks", "Queues"],
    result: "Repeatable automations with run logs",
    category: "AUTOMATION",
    status: "SHIPPED",
    year: 2025,
  },
  {
    slug: "mvp-kit",
    title: "MVP Starter Experiments",
    summary: "Reusable auth, billing, and shell patterns.",
    problem: "Every new idea restarts from zero scaffolding.",
    role: "Product engineer",
    tech: ["Auth", "Stripe", "Feature flags"],
    result: "Faster idea → first users cycle",
    category: "EXPERIMENTS",
    status: "BUILDING",
    year: 2026,
  },
  {
    slug: "client-growth",
    title: "Client Growth Systems",
    summary: "SEO + conversion systems for e-commerce brands.",
    problem: "Brands need compounding organic acquisition.",
    role: "Consultant / builder",
    tech: ["SEO", "Content", "CRO"],
    result: "Documented growth playbooks and shipped sites",
    category: "CLIENT",
    status: "SHIPPED",
    year: 2023,
  },
  {
    slug: "internal-tools",
    title: "Internal Builder Tools",
    summary: "Small tools that remove friction from shipping.",
    problem: "Founders lose time to glue work.",
    role: "Maker",
    tech: ["Node", "CLI", "Scripts"],
    result: "Reusable utilities across products",
    category: "TOOLS",
    status: "ARCHIVED",
    year: 2024,
  },
];

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
