import type { Tool } from "./tools";

type ToolInput = Omit<
  Tool,
  "category" | "relatedProductSlug" | "relatedProductUrl" | "relatedProductLabel" | "processing"
> & { accent?: string };

function spainTool(partial: ToolInput): Tool {
  return {
    category: "spain",
    relatedProductSlug: "spain-eats",
    relatedProductUrl: "https://spaineats.info/",
    relatedProductLabel: "Spain Eats",
    processing: "local",
    accent: partial.accent ?? "#3dd6c6",
    slug: partial.slug,
    en: partial.en,
    es: partial.es,
  };
}

/** Free Spain life / finance / education tools — all client-side. */
export const spainLifeTools: Tool[] = [
  spainTool({
    slug: "crear-cv-profesional",
    accent: "#7dd3fc",
    en: {
      name: "Free professional CV builder",
      title: "Free Professional CV Builder for Spain — ATS Two-Column Resume",
      description:
        "Create a free ATS-friendly resume online with a modern two-column layout for Spanish job applications. Print to PDF in your browser.",
      h1: "Create a professional CV for free",
      intro:
        "Build a clean, ATS-oriented CV tailored for Spain hiring flows. Edit locally, preview a two-column layout, then print to PDF or download plain text — no signup.",
      benefit: "ATS-friendly two-column CV, free in your browser.",
      howTo: ["Fill name, role, experience, education, and skills.", "Preview the two-column layout.", "Print to PDF or download .txt."],
      whatItDoes: "Generates a printable CV structure optimized for clarity and ATS parsing.",
      whatItDoesNot: "It does not auto-submit to job boards or guarantee interview outcomes.",
      tips: ["Keep bullets results-first.", "Export PDF via the browser print dialog.", "Match keywords from the job post."],
      faq: [
        { q: "Is it really free?", a: "Yes. 100% free, runs in your browser, no account." },
        { q: "Is it ATS friendly?", a: "The layout stays text-based with clear headings — good for most ATS parsers." },
      ],
    },
    es: {
      name: "Crear CV profesional gratis",
      title: "Crear CV profesional gratis — Plantilla ATS dos columnas España",
      description:
        "Crea un currículum ATS gratis con diseño moderno de dos columnas para ofertas en España. Imprime a PDF desde el navegador.",
      h1: "Crear CV profesional gratis",
      intro:
        "Monta un CV limpio orientado a ATS para procesos de selección en España. Edita en local, previsualiza dos columnas e imprime a PDF o descarga texto — sin registro.",
      benefit: "CV ATS de dos columnas, gratis en el navegador.",
      howTo: ["Completa nombre, puesto, experiencia, formación y skills.", "Revisa la vista previa.", "Imprime a PDF o descarga .txt."],
      whatItDoes: "Genera una estructura de CV imprimible clara y compatible con ATS.",
      whatItDoesNot: "No envía candidaturas ni garantiza entrevistas.",
      tips: ["Viñetas con resultados.", "PDF desde imprimir del navegador.", "Alinea keywords de la oferta."],
      faq: [
        { q: "¿Es gratis?", a: "Sí. 100% gratis, en tu navegador, sin cuenta." },
        { q: "¿Vale para ATS?", a: "Es texto con encabezados claros — compatible con la mayoría de ATS." },
      ],
    },
  }),
  spainTool({
    slug: "calculadora-evau-2026",
    accent: "#a78bfa",
    en: {
      name: "EvAU 2026 score calculator",
      title: "EvAU 2026 Calculator — University Admission Score Simulator Spain",
      description:
        "Calculate your EvAU 2026 admission grade from Bachillerato, general phase, and specific subjects with university weights.",
      h1: "EvAU 2026 admission score calculator",
      intro:
        "Simulate your Spanish university access and admission grades for 2026 using the standard 0.6×Bach + 0.4×general formula plus specific-phase weights.",
      benefit: "Simulate EvAU access and admission scores instantly.",
      howTo: ["Enter Bachillerato average.", "Add general EvAU grade.", "Set specific subjects and 0.1/0.2 weights."],
      whatItDoes: "Computes access grade and admission grade up to 14.",
      whatItDoesNot: "Does not replace official university cut-offs or convocatoria rules.",
      tips: ["Confirm ponderaciones on your target degree page.", "Try multiple weight combinations."],
      faq: [
        { q: "What is the max score?", a: "Admission can reach 14 with two highly weighted specific subjects." },
        { q: "Is 2026 different?", a: "Core formula is stable; always verify weights for the convocatoria you sit." },
      ],
    },
    es: {
      name: "Calculadora EvAU 2026",
      title: "Calculadora EvAU 2026 — Simulador nota de admisión universidad",
      description:
        "Calcula tu nota de admisión EvAU 2026 con Bachillerato, fase obligatoria y específicas con ponderaciones universitarias.",
      h1: "Calculadora de nota EvAU 2026",
      intro:
        "Simula tu nota de acceso y admisión universitaria 2026 con la fórmula 0,6×Bach + 0,4×obligatoria más ponderaciones de la fase específica.",
      benefit: "Simula notas de acceso y admisión EvAU al instante.",
      howTo: ["Introduce la media de Bachillerato.", "Añade la fase obligatoria.", "Configura específicas y pesos 0,1/0,2."],
      whatItDoes: "Calcula nota de acceso y de admisión (hasta 14).",
      whatItDoesNot: "No sustituye notas de corte oficiales ni reglas de convocatoria.",
      tips: ["Confirma ponderaciones en la web de tu grado.", "Prueba varias combinaciones de pesos."],
      faq: [
        { q: "¿Cuál es la nota máxima?", a: "La admisión puede llegar a 14 con dos específicas bien ponderadas." },
        { q: "¿Cambia en 2026?", a: "La fórmula base es estable; verifica siempre los pesos de tu convocatoria." },
      ],
    },
  }),
  spainTool({
    slug: "calculadora-nota-media",
    accent: "#a78bfa",
    en: {
      name: "Grade average calculator",
      title: "Grade Average Calculator — ESO, Bachillerato, FP & University",
      description: "Calculate simple or weighted grade averages for ESO, Bachillerato, FP, or university courses — free and instant.",
      h1: "Grade average calculator",
      intro: "Paste your subject grades (and optional weights) to get an accurate arithmetic or weighted average for Spanish education tracks.",
      benefit: "Fast averages for school, FP, and university.",
      howTo: ["Enter grades separated by commas.", "Optionally add matching weights.", "Read the average."],
      whatItDoes: "Computes simple or weighted means from your list.",
      whatItDoesNot: "Does not certify official expediente grades.",
      tips: ["Use weights for créditos ECTS.", "Keep the same grade scale (usually 0–10)."],
      faq: [
        { q: "Can I weight by credits?", a: "Yes — provide one weight per grade." },
        { q: "Which levels?", a: "ESO, Bachillerato, FP, and university all work if grades share a scale." },
      ],
    },
    es: {
      name: "Calculadora de nota media",
      title: "Calculadora de nota media — ESO, Bachillerato, FP y universidad",
      description: "Calcula la media aritmética o ponderada para ESO, Bachillerato, FP o universidad — gratis e inmediata.",
      h1: "Calculadora de nota media",
      intro: "Pega tus notas (y pesos opcionales) para obtener la media aritmética o ponderada en itinerarios educativos españoles.",
      benefit: "Medias rápidas para colegio, FP y universidad.",
      howTo: ["Introduce notas separadas por comas.", "Opcionalmente añade pesos.", "Lee la media."],
      whatItDoes: "Calcula medias simples o ponderadas.",
      whatItDoesNot: "No certifica el expediente oficial.",
      tips: ["Usa pesos para créditos ECTS.", "Mantén la misma escala (normalmente 0–10)."],
      faq: [
        { q: "¿Puedo ponderar por créditos?", a: "Sí — un peso por cada nota." },
        { q: "¿Qué niveles cubre?", a: "ESO, Bachillerato, FP y universidad si comparten escala." },
      ],
    },
  }),
  spainTool({
    slug: "smart-deal-finder",
    accent: "#fbbf24",
    en: {
      name: "Smart Deal Finder",
      title: "Smart Deal Finder — Free Promo & Discount Store Directory Spain",
      description: "Find popular Spanish and EU stores for deals, discounts, and promo-code hunting — free curated directory.",
      h1: "Smart Deal Finder",
      intro: "Filter a curated list of stores that frequently run promos in Spain/EU. Jump out to the retailer — no signup, no scraping claims.",
      benefit: "Quick directory of deal-heavy stores.",
      howTo: ["Search by store or category.", "Filter tech, travel, codes, etc.", "Open the retailer."],
      whatItDoes: "Helps you discover where to look for offers.",
      whatItDoesNot: "Does not scrape live prices or guarantee active coupons.",
      tips: ["Pair with cashback apps carefully.", "Check shipping to islands."],
      faq: [
        { q: "Are coupons verified?", a: "No — this is a store directory, not a live coupon API." },
        { q: "Is it free?", a: "Yes, completely free." },
      ],
    },
    es: {
      name: "Smart Deal Finder",
      title: "Smart Deal Finder — Ofertas, descuentos y cupones (directorio gratis)",
      description: "Encuentra tiendas ES/UE con ofertas frecuentes, descuentos y cupones — directorio gratuito.",
      h1: "Smart Deal Finder",
      intro: "Filtra una lista curada de tiendas con promos habituales en España/UE. Salta al retailer — sin registro ni promesas de scraping.",
      benefit: "Directorio rápido de tiendas con ofertas.",
      howTo: ["Busca tienda o categoría.", "Filtra tech, viajes, cupones…", "Abre la tienda."],
      whatItDoes: "Te orienta dónde buscar ofertas.",
      whatItDoesNot: "No scrapea precios ni garantiza cupones activos.",
      tips: ["Combina con cashback con cuidado.", "Revisa envíos a islas."],
      faq: [
        { q: "¿Cupones verificados?", a: "No — es un directorio, no una API de cupones." },
        { q: "¿Es gratis?", a: "Sí, totalmente gratis." },
      ],
    },
  }),
  spainTool({
    slug: "planificador-de-dieta",
    accent: "#4ade80",
    en: {
      name: "Diet planner",
      title: "Free Diet Planner — Calories, Macros, BMI & Water Intake",
      description: "Plan daily calories and macros, estimate BMI and water needs with Mifflin–St Jeor — free browser diet planner.",
      h1: "Diet planner (calories & macros)",
      intro: "Estimate BMR, TDEE, target calories, protein/fat/carbs, BMI, and water intake for lose / maintain / gain goals.",
      benefit: "Calories, macros, BMI, and water in one tool.",
      howTo: ["Enter sex, age, height, weight.", "Pick activity and goal.", "Follow target kcal + macros."],
      whatItDoes: "Uses Mifflin–St Jeor with activity multipliers.",
      whatItDoesNot: "Not medical advice or a meal delivery plan.",
      tips: ["Recalculate after weight changes.", "Prioritize protein when cutting."],
      faq: [
        { q: "Which formula?", a: "Mifflin–St Jeor for BMR, then activity factor for TDEE." },
        { q: "Is data stored?", a: "No — everything stays in your browser session." },
      ],
    },
    es: {
      name: "Planificador de dieta",
      title: "Planificador de dieta gratis — Calorías, macros, IMC y agua",
      description: "Planifica calorías y macros, estima IMC y agua con Mifflin–St Jeor — planificador gratis en el navegador.",
      h1: "Planificador de dieta (calorías y macros)",
      intro: "Estima BMR, TDEE, calorías objetivo, proteínas/grasas/carbos, IMC y agua para perder / mantener / ganar.",
      benefit: "Calorías, macros, IMC y agua en una herramienta.",
      howTo: ["Introduce sexo, edad, altura y peso.", "Elige actividad y objetivo.", "Sigue kcal + macros."],
      whatItDoes: "Usa Mifflin–St Jeor con factores de actividad.",
      whatItDoesNot: "No es consejo médico ni un menú a domicilio.",
      tips: ["Recalcula si cambia el peso.", "Prioriza proteína en déficit."],
      faq: [
        { q: "¿Qué fórmula?", a: "Mifflin–St Jeor para BMR y factor de actividad para TDEE." },
        { q: "¿Se guardan datos?", a: "No — todo queda en tu sesión del navegador." },
      ],
    },
  }),
  spainTool({
    slug: "calculadora-de-salario",
    accent: "#34d399",
    en: {
      name: "Spain salary calculator",
      title: "Spain Net Salary Calculator — Gross to Net Monthly & Annual",
      description: "Estimate net monthly and annual salary in Spain from gross pay with IRPF brackets and employee Social Security.",
      h1: "Spain salary calculator (gross → net)",
      intro: "Convert Spanish gross annual salary into estimated net monthly and annual pay with orientative IRPF and employee SS rates.",
      benefit: "Quick gross-to-net estimate for Spain.",
      howTo: ["Enter gross annual salary.", "Choose 12 or 14 payments.", "Adjust employee SS % if needed."],
      whatItDoes: "Applies simplified IRPF brackets + SS employee share.",
      whatItDoesNot: "Not a payroll engine — ignores many personal deductions.",
      tips: ["Use 14 pagas if your contract has extras.", "Compare offers on net, not only gross."],
      faq: [
        { q: "Accurate for my CCAA?", a: "It is national-orientative; regional details can differ." },
        { q: "Includes employer SS?", a: "No — this focuses on employee net take-home." },
      ],
    },
    es: {
      name: "Calculadora de salario",
      title: "Calculadora de salario neto España — Bruto a neto mensual y anual",
      description: "Estima el salario neto mensual y anual en España a partir del bruto con tramos IRPF y SS del trabajador.",
      h1: "Calculadora de salario (bruto → neto)",
      intro: "Convierte el bruto anual español en neto mensual/anual estimado con IRPF orientativo y cotización del trabajador.",
      benefit: "Estimación rápida bruto→neto en España.",
      howTo: ["Introduce bruto anual.", "Elige 12 o 14 pagas.", "Ajusta % SS si hace falta."],
      whatItDoes: "Aplica tramos IRPF simplificados + SS trabajador.",
      whatItDoesNot: "No es un motor de nómina — ignora muchas deducciones personales.",
      tips: ["Usa 14 pagas si tu contrato las tiene.", "Compara ofertas en neto, no solo bruto."],
      faq: [
        { q: "¿Vale para mi CCAA?", a: "Es orientativo estatal; detalles regionales pueden variar." },
        { q: "¿Incluye SS empresa?", a: "No — se centra en el neto del trabajador." },
      ],
    },
  }),
  spainTool({
    slug: "planificador-de-presupuesto",
    accent: "#60a5fa",
    en: {
      name: "Budget planner",
      title: "Free Budget Planner — Income, Expenses & Savings Rate",
      description: "Manage monthly income and expenses, monitor spending categories, and calculate your savings rate — free.",
      h1: "Budget planner",
      intro: "Map income vs housing, food, transport, subscriptions, and other costs to see leftover cash and savings rate.",
      benefit: "See spending and savings rate clearly.",
      howTo: ["Enter net income.", "Fill expense categories.", "Read leftover + savings %."],
      whatItDoes: "Sums categories and computes savings rate.",
      whatItDoesNot: "Does not sync to banks.",
      tips: ["Aim for ≥20% savings when possible.", "Cut subscriptions first."],
      faq: [
        { q: "Is data uploaded?", a: "No — calculations stay on-device." },
        { q: "Currency?", a: "Euro-oriented formatting; amounts are whatever you enter." },
      ],
    },
    es: {
      name: "Planificador de presupuesto",
      title: "Planificador de presupuesto gratis — Ingresos, gastos y tasa de ahorro",
      description: "Gestiona ingresos y gastos mensuales, controla categorías y calcula tu tasa de ahorro — gratis.",
      h1: "Planificador de presupuesto",
      intro: "Compara ingresos con vivienda, comida, transporte, suscripciones y otros para ver el sobrante y la tasa de ahorro.",
      benefit: "Gastos y tasa de ahorro claros.",
      howTo: ["Introduce ingresos netos.", "Rellena categorías.", "Mira sobrante + % ahorro."],
      whatItDoes: "Suma categorías y calcula la tasa de ahorro.",
      whatItDoesNot: "No se conecta a bancos.",
      tips: ["Objetivo ≥20% si puedes.", "Recorta suscripciones primero."],
      faq: [
        { q: "¿Se suben datos?", a: "No — el cálculo es local." },
        { q: "¿Moneda?", a: "Formato en euros; los importes son los que introduzcas." },
      ],
    },
  }),
  spainTool({
    slug: "estimador-de-envios",
    accent: "#fb923c",
    en: {
      name: "Shipping cost estimator",
      title: "Shipping Cost Estimator — Spain, Islands, EU & International",
      description: "Estimate parcel shipping cost and delivery time for Spain mainland, islands, EU, and international lanes.",
      h1: "Shipping estimator",
      intro: "Get a quick orientative price and ETA based on weight, destination zone, and standard vs express service.",
      benefit: "Ballpark parcel cost and delivery window.",
      howTo: ["Enter weight in kg.", "Pick destination zone.", "Choose standard or express."],
      whatItDoes: "Applies a simple zone + weight pricing model.",
      whatItDoesNot: "Not a live carrier quote from Correos or private networks.",
      tips: ["Islands usually cost more.", "Compare at least two carriers."],
      faq: [
        { q: "Accurate quote?", a: "Orientation only — confirm with the carrier checkout." },
        { q: "Includes customs?", a: "No — international VAT/duties are excluded." },
      ],
    },
    es: {
      name: "Estimador de envíos",
      title: "Estimador de envíos — Península, islas, UE e internacional",
      description: "Estima coste y plazo de paquetería para península, islas, UE e internacional.",
      h1: "Estimador de envíos",
      intro: "Obtén un precio y plazo orientativos según peso, zona y servicio estándar o exprés.",
      benefit: "Orden de magnitud de coste y entrega.",
      howTo: ["Introduce peso en kg.", "Elige destino.", "Elige estándar o exprés."],
      whatItDoes: "Aplica un modelo simple de zona + peso.",
      whatItDoesNot: "No es una tarifa en vivo de Correos u otros.",
      tips: ["Las islas suelen costar más.", "Compara al menos dos operadores."],
      faq: [
        { q: "¿Es exacto?", a: "Orientativo — confirma en el checkout del carrier." },
        { q: "¿Aduanas?", a: "No — IVA/aranceles internacionales no incluidos." },
      ],
    },
  }),
  spainTool({
    slug: "calculadora-de-hipoteca",
    accent: "#f472b6",
    en: {
      name: "Mortgage calculator",
      title: "Spain Mortgage Calculator — Monthly Payment, Interest & Euribor",
      description: "Calculate monthly mortgage payments, total interest, and LTV for fixed or Euribor + spread variable loans in Spain.",
      h1: "Mortgage calculator",
      intro: "Estimate Spanish home-loan monthly payments for fixed rates or variable Euribor + differential, including total interest and LTV.",
      benefit: "Monthly quota, interest, and LTV in seconds.",
      howTo: ["Enter price and down payment.", "Set term years.", "Choose fixed or variable rate inputs."],
      whatItDoes: "Uses standard amortization math.",
      whatItDoesNot: "Excludes insurance, fees, and ITP/AJD taxes.",
      tips: ["Stress-test +1% rate.", "Keep LTV ≤80% when possible."],
      faq: [
        { q: "Variable formula?", a: "Annual rate ≈ Euribor + spread, then monthly amortization." },
        { q: "Includes bank fees?", a: "No — add opening fees separately." },
      ],
    },
    es: {
      name: "Calculadora de hipoteca",
      title: "Calculadora de hipoteca España — Cuota, intereses y Euribor",
      description: "Calcula la cuota mensual, intereses totales y LTV para hipoteca fija o variable Euribor + diferencial.",
      h1: "Calculadora de hipoteca",
      intro: "Estima la cuota de hipoteca en España a tipo fijo o variable (Euribor + diferencial), con intereses totales y LTV.",
      benefit: "Cuota, intereses y LTV en segundos.",
      howTo: ["Introduce precio y entrada.", "Define plazo.", "Elige fijo o variable."],
      whatItDoes: "Usa amortización francesa estándar.",
      whatItDoesNot: "No incluye seguros, comisiones ni ITP/AJD.",
      tips: ["Prueba +1% de tipo.", "Intenta LTV ≤80%."],
      faq: [
        { q: "¿Variable?", a: "Tipo anual ≈ Euribor + diferencial, luego cuota mensual." },
        { q: "¿Comisiones?", a: "No — súmalas aparte." },
      ],
    },
  }),
  spainTool({
    slug: "validador-dni-nie",
    accent: "#38bdf8",
    en: {
      name: "DNI / NIE validator",
      title: "Spanish DNI / NIE Validator — Check or Calculate Control Letter",
      description: "Validate Spanish DNI or NIE numbers or calculate the correct control letter securely in your browser — free.",
      h1: "DNI / NIE validator",
      intro: "Check DNI and NIE checksum letters locally using the official modulo-23 alphabet. Nothing is uploaded.",
      benefit: "Validate or compute the control letter on-device.",
      howTo: ["Paste DNI or NIE.", "See validity or expected letter.", "Fix typos before forms."],
      whatItDoes: "Implements the standard letter algorithm.",
      whatItDoesNot: "Does not verify identity with government databases.",
      tips: ["NIE starts with X, Y, or Z.", "Works offline after page load."],
      faq: [
        { q: "Is my ID sent anywhere?", a: "No — validation is 100% local." },
        { q: "Can it invent a valid ID?", a: "It only checks/format-completes letters; it cannot create legal IDs." },
      ],
    },
    es: {
      name: "Validador de DNI / NIE",
      title: "Validador DNI / NIE — Comprueba o calcula la letra de control",
      description: "Valida DNI o NIE españoles o calcula la letra correcta de forma segura en tu dispositivo — gratis.",
      h1: "Validador de DNI / NIE",
      intro: "Comprueba la letra de control de DNI y NIE en local con el alfabeto módulo 23 oficial. No se sube nada.",
      benefit: "Valida o calcula la letra en tu dispositivo.",
      howTo: ["Pega el DNI o NIE.", "Mira validez o letra esperada.", "Corrige typos antes de formularios."],
      whatItDoes: "Implementa el algoritmo estándar de letra.",
      whatItDoesNot: "No verifica identidad en bases gubernamentales.",
      tips: ["El NIE empieza por X, Y o Z.", "Funciona offline tras cargar."],
      faq: [
        { q: "¿Se envía mi documento?", a: "No — 100% local." },
        { q: "¿Puede inventar un DNI?", a: "Solo comprueba/completa la letra; no crea documentos legales." },
      ],
    },
  }),
  spainTool({
    slug: "calculadora-de-finiquito",
    accent: "#e879f9",
    en: {
      name: "Severance / finiquito calculator",
      title: "Spain Finiquito Calculator — Severance, Vacation & Pending Pay",
      description: "Estimate Spanish severance (finiquito) including indemnity days, unused vacation, and pending extras — free guidance tool.",
      h1: "Finiquito calculator",
      intro: "Estimate dismissal indemnity (20 or 33 days/year), unused vacation pay, and pending prorations for Spanish employment exits.",
      benefit: "Orientative finiquito total in euros.",
      howTo: ["Enter monthly salary and tenure.", "Pick dismissal type.", "Add vacation days and extras."],
      whatItDoes: "Applies common statutory day tables with caps.",
      whatItDoesNot: "Does not replace a labour lawyer or convenio rules.",
      tips: ["Check your convenio for improvements.", "Keep payslips for the daily base."],
      faq: [
        { q: "33 vs 20 days?", a: "Unfair dismissal often uses 33; objective dismissal commonly 20 — confirm legally." },
        { q: "Contract end?", a: "Many temporary ends lack statutory indemnity — vacation/extras may still apply." },
      ],
    },
    es: {
      name: "Calculadora de finiquito",
      title: "Calculadora de finiquito — Indemnización, vacaciones y pagas",
      description: "Estima el finiquito en España con indemnización, vacaciones pendientes y prorratas — herramienta orientativa gratis.",
      h1: "Calculadora de finiquito",
      intro: "Estima indemnización por despido (20 o 33 días/año), vacaciones no disfrutadas y prorratas pendientes.",
      benefit: "Total orientativo de finiquito en euros.",
      howTo: ["Introduce salario y antigüedad.", "Elige tipo de salida.", "Añade vacaciones y extras."],
      whatItDoes: "Aplica tablas habituales de días con topes.",
      whatItDoesNot: "No sustituye a un laboralista ni al convenio.",
      tips: ["Revisa mejoras de convenio.", "Guarda nóminas para la base diaria."],
      faq: [
        { q: "¿33 o 20 días?", a: "Improcedente suele 33; objetivo suele 20 — confírmalo legalmente." },
        { q: "¿Fin de contrato?", a: "Muchos temporales no tienen indemnización tipificada — vacaciones/extras sí pueden aplicar." },
      ],
    },
  }),
  spainTool({
    slug: "cuota-de-autonomos",
    accent: "#facc15",
    en: {
      name: "Autónomos quota calculator",
      title: "Cuota de Autónomos Calculator — Estimate Monthly Self-Employed SS",
      description: "Estimate monthly Spanish autónomo Social Security contributions from net earnings or flat-rate start — free 2026-oriented tool.",
      h1: "Autónomos quota calculator",
      intro: "Ballpark your monthly self-employed contribution from estimated net monthly earnings, with an optional early flat-rate mode.",
      benefit: "Monthly cuota estimate from net earnings.",
      howTo: ["Enter estimated monthly net.", "Toggle flat rate if newly registered.", "Read base + cuota."],
      whatItDoes: "Maps simplified brackets to contribution bases.",
      whatItDoesNot: "Not official Importass output.",
      tips: ["Track real net quarterly.", "Ask a gestoría before changing base."],
      faq: [
        { q: "Official?", a: "Orientative — confirm in Importass / advisor." },
        { q: "Flat rate?", a: "Early months can be reduced; rules change — verify current campaign." },
      ],
    },
    es: {
      name: "Cuota de autónomos",
      title: "Calculadora cuota de autónomos — Estimación mensual SS",
      description: "Estima la cuota mensual de autónomos según rendimiento neto o tarifa plana — herramienta orientativa 2026 gratis.",
      h1: "Calculadora de cuota de autónomos",
      intro: "Calcula una cuota mensual orientativa a partir del rendimiento neto mensual estimado, con modo tarifa plana inicial opcional.",
      benefit: "Estimación de cuota desde rendimientos netos.",
      howTo: ["Introduce neto mensual estimado.", "Activa tarifa plana si eres alta nueva.", "Lee base + cuota."],
      whatItDoes: "Asocia tramos simplificados a bases de cotización.",
      whatItDoesNot: "No es el resultado oficial de Importass.",
      tips: ["Sigue el neto real trimestral.", "Consulta gestoría antes de cambiar base."],
      faq: [
        { q: "¿Oficial?", a: "Orientativo — confirma en Importass / asesor." },
        { q: "¿Tarifa plana?", a: "Los primeros meses pueden reducirse; verifica la campaña vigente." },
      ],
    },
  }),
  spainTool({
    slug: "calculadora-fecha-de-parto",
    accent: "#f9a8d4",
    en: {
      name: "Due date calculator",
      title: "Pregnancy Due Date Calculator — Week, Milestones & ETA",
      description: "Estimate due date, current pregnancy week, and key milestones from last menstrual period — free Naegele guidance tool.",
      h1: "Pregnancy due date calculator",
      intro: "Enter your LMP to estimate due date (~280 days), current week+day, days remaining, and trimester milestones.",
      benefit: "Due date, week, and milestones instantly.",
      howTo: ["Pick last menstrual period date.", "Read due date and current week.", "Review milestone dates."],
      whatItDoes: "Applies Naegele’s rule locally.",
      whatItDoesNot: "Not a medical diagnosis — confirm with your clinician.",
      tips: ["Ultrasound dating may adjust ETA.", "Track symptoms separately with your care team."],
      faq: [
        { q: "Why 280 days?", a: "Standard obstetric estimate from LMP (40 weeks)." },
        { q: "Private data?", a: "Stays in your browser only." },
      ],
    },
    es: {
      name: "Calculadora de fecha de parto",
      title: "Calculadora fecha de parto — Semana, hitos y FPP",
      description: "Estima la fecha probable de parto, semana de gestación e hitos desde la FUM — herramienta gratis (Naegele).",
      h1: "Calculadora de fecha de parto",
      intro: "Introduce la FUM para estimar la FPP (~280 días), semana+día actual, días restantes e hitos del embarazo.",
      benefit: "FPP, semana e hitos al instante.",
      howTo: ["Elige la fecha de última menstruación.", "Lee FPP y semana actual.", "Revisa hitos."],
      whatItDoes: "Aplica la regla de Naegele en local.",
      whatItDoesNot: "No es diagnóstico médico — confirma con tu profesional.",
      tips: ["La ecografía puede ajustar la FPP.", "Sigue síntomas con tu equipo sanitario."],
      faq: [
        { q: "¿Por qué 280 días?", a: "Estimación obstétrica estándar desde FUM (40 semanas)." },
        { q: "¿Datos privados?", a: "Solo en tu navegador." },
      ],
    },
  }),
];
